version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8098:8000" # Ajuste a porta conforme necessário
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"